TEXT = {
    "title": "建筑巡检智能助手",
    "login_required": "请先登录。",
    "invalid_credentials": "用户名或密码错误。",
    "login_success": "登录成功。",
    "register_success": "注册成功，请登录。",
    "register_exists": "用户名已存在。",
    "register_empty": "用户名和密码不能为空。",
    "register_mismatch": "两次输入的密码不一致。",
    "register_short_password": "密码长度至少为 6 位。",
    "no_image": "未接收到图片。",
    "encode_failed": "图片编码失败。",
    "inspect_failed": "巡检失败",
    "no_report": "未生成报告。",
    "llm_no_context": "请先完成一次巡检，再进行问答。",
    "llm_no_api_key": "未配置 EMBEDDING_API_KEY，请在 .env 中设置后重启应用。",
}
